# Generated by Django 4.1.6 on 2023-04-04 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0007_remove_employer_task_employee_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.employer')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.task')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.employee')),
            ],
        ),
    ]
