# Generated by Django 4.1.6 on 2023-02-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_task', models.CharField(max_length=255)),
                ('task', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('date_of_releas', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='task',
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='count_of_completed_task',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='skills',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
