# Generated by Django 4.1.6 on 2023-02-16 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_remove_employee_task_remove_task_description_of_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='task',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='work.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='descriptions_task',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
