# Generated by Django 4.1.6 on 2023-04-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_remove_employer_task_employee_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='descriptions_task',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
