# Generated by Django 4.1.6 on 2023-02-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activity',
            field=models.CharField(choices=[('employee', 'employee'), ('employer', 'employer')], max_length=20, null=True),
        ),
    ]
