# Generated by Django 4.1.6 on 2023-02-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_work_remove_account_task_account_bio_and_more'),
        ('authentication', '0003_customuser_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.account'),
        ),
    ]
