# Generated by Django 4.1.6 on 2023-02-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activity',
            field=models.CharField(choices=[('employee', 'employee'), ('employer', 'employer')], max_length=255, null=True),
        ),
    ]
